#! /bin/zsh

setopt err_exit no_unset warn_create_global

autoload -U zargs

mkdir --parents bullseye bookworm trixie
mkdir --parents .etags

base=https://deb.debian.org/

for location (
    debian/dists/bullseye/InRelease \
    debian/dists/bullseye/contrib/binary-i386/Packages.xz \
    debian/dists/bullseye/contrib/i18n/Translation-en.bz2 \
    debian/dists/bullseye/main/binary-i386/Packages.xz \
    debian/dists/bullseye/main/i18n/Translation-en.bz2 \
    debian/dists/bullseye/non-free/binary-i386/Packages.xz \
    debian/dists/bullseye/non-free/i18n/Translation-en.bz2 \
    debian/dists/bullseye-updates/InRelease \
    debian/dists/bullseye-updates/contrib/binary-i386/Packages.xz \
    debian/dists/bullseye-updates/contrib/i18n/Translation-en.bz2 \
    debian/dists/bullseye-updates/main/binary-i386/Packages.xz \
    debian/dists/bullseye-updates/main/i18n/Translation-en.bz2 \
    debian/dists/bullseye-updates/non-free/binary-i386/Packages.xz \
    debian/dists/bullseye-updates/non-free/i18n/Translation-en.bz2 \
    debian-security/dists/bullseye-security/InRelease \
    debian-security/dists/bullseye-security/contrib/binary-i386/Packages.xz \
    debian-security/dists/bullseye-security/contrib/i18n/Translation-en.xz \
    debian-security/dists/bullseye-security/main/binary-i386/Packages.xz \
    debian-security/dists/bullseye-security/main/i18n/Translation-en.xz \
    debian-security/dists/bullseye-security/non-free/binary-i386/Packages.xz \
    debian-security/dists/bullseye-security/non-free/i18n/Translation-en.xz
) {
    url=$base$location
    safename=${${url/#https:\/\/}//\//_}
    filename=bullseye/$safename
    output=${filename/%.(bz2|xz)}
    etagname=.etags/$safename
    [[ -f $output ]] && ref_time=$output || ref_time="2004 Nov 13"
    echo "--- $url"
    curl --connect-timeout 5 --max-time 30 \
        --etag-compare $etagname \
        --etag-save $etagname \
        --time-cond $ref_time --output $filename $url
}

for location (
    debian/dists/bookworm/InRelease \
    debian/dists/bookworm/contrib/binary-amd64/Packages.xz \
    debian/dists/bookworm/contrib/i18n/Translation-en.xz \
    debian/dists/bookworm/main/binary-amd64/Packages.xz \
    debian/dists/bookworm/main/i18n/Translation-en.xz \
    debian/dists/bookworm/non-free/binary-amd64/Packages.xz \
    debian/dists/bookworm/non-free/i18n/Translation-en.xz \
    debian/dists/bookworm/non-free-firmware/binary-amd64/Packages.xz \
    debian/dists/bookworm/non-free-firmware/i18n/Translation-en.xz \
    debian/dists/bookworm-updates/InRelease \
    debian/dists/bookworm-updates/contrib/binary-amd64/Packages.xz \
    debian/dists/bookworm-updates/contrib/i18n/Translation-en.xz \
    debian/dists/bookworm-updates/main/binary-amd64/Packages.xz \
    debian/dists/bookworm-updates/main/i18n/Translation-en.xz \
    debian/dists/bookworm-updates/non-free/binary-amd64/Packages.xz \
    debian/dists/bookworm-updates/non-free/i18n/Translation-en.xz \
    debian/dists/bookworm-updates/non-free-firmware/binary-amd64/Packages.xz \
    debian/dists/bookworm-updates/non-free-firmware/i18n/Translation-en.xz \
    debian-security/dists/bookworm-security/InRelease \
    debian-security/dists/bookworm-security/contrib/binary-amd64/Packages.xz \
    debian-security/dists/bookworm-security/contrib/i18n/Translation-en.xz \
    debian-security/dists/bookworm-security/main/binary-amd64/Packages.xz \
    debian-security/dists/bookworm-security/main/i18n/Translation-en.xz \
    debian-security/dists/bookworm-security/non-free/binary-amd64/Packages.xz \
    debian-security/dists/bookworm-security/non-free/i18n/Translation-en.xz
    debian-security/dists/bookworm-security/non-free-firmware/binary-amd64/Packages.xz \
    debian-security/dists/bookworm-security/non-free-firmware/i18n/Translation-en.xz
) {
    url=$base$location
    safename=${${url/#https:\/\/}//\//_}
    filename=bookworm/$safename
    output=${filename/%.xz}
    etagname=.etags/$safename
    [[ -f $output ]] && ref_time=$output || ref_time="2004 Nov 13"
    echo "--- $url"
    curl --connect-timeout 5 --max-time 30 \
        --etag-compare $etagname \
        --etag-save $etagname \
        --time-cond $ref_time --output $filename $url
}

for location (
    debian/dists/trixie/InRelease \
    debian/dists/trixie/contrib/binary-amd64/Packages.xz \
    debian/dists/trixie/contrib/i18n/Translation-en.xz \
    debian/dists/trixie/main/binary-amd64/Packages.xz \
    debian/dists/trixie/main/i18n/Translation-en.xz \
    debian/dists/trixie/non-free/binary-amd64/Packages.xz \
    debian/dists/trixie/non-free/i18n/Translation-en.xz \
    debian/dists/trixie/non-free-firmware/binary-amd64/Packages.xz \
    debian/dists/trixie/non-free-firmware/i18n/Translation-en.xz \
    debian/dists/trixie-updates/InRelease \
    debian/dists/trixie-updates/contrib/binary-amd64/Packages.xz \
    debian/dists/trixie-updates/contrib/i18n/Translation-en.xz \
    debian/dists/trixie-updates/main/binary-amd64/Packages.xz \
    debian/dists/trixie-updates/main/i18n/Translation-en.xz \
    debian/dists/trixie-updates/non-free/binary-amd64/Packages.xz \
    debian/dists/trixie-updates/non-free/i18n/Translation-en.xz \
    debian/dists/trixie-updates/non-free-firmware/binary-amd64/Packages.xz \
    debian/dists/trixie-updates/non-free-firmware/i18n/Translation-en.xz \
    debian-security/dists/trixie-security/InRelease \
    debian-security/dists/trixie-security/contrib/binary-amd64/Packages.xz \
    debian-security/dists/trixie-security/contrib/i18n/Translation-en.xz \
    debian-security/dists/trixie-security/main/binary-amd64/Packages.xz \
    debian-security/dists/trixie-security/main/i18n/Translation-en.xz \
    debian-security/dists/trixie-security/non-free/binary-amd64/Packages.xz \
    debian-security/dists/trixie-security/non-free/i18n/Translation-en.xz
    debian-security/dists/trixie-security/non-free-firmware/binary-amd64/Packages.xz \
    debian-security/dists/trixie-security/non-free-firmware/i18n/Translation-en.xz
) {
    url=$base$location
    safename=${${url/#https:\/\/}//\//_}
    filename=trixie/$safename
    output=${filename/%.xz}
    etagname=.etags/$safename
    echo "--- $url"
    curl --connect-timeout 5 --max-time 30 \
        --etag-compare $etagname \
        --etag-save $etagname \
        --time-cond $ref_time --output $filename $url
}

zargs --max-args 3 --max-procs $(nproc) --no-run-if-empty -- \
    {bullseye,bookworm,trixie}/*.xz(N) -- \
    unxz --force --verbose
zargs --max-args 3 --max-procs $(nproc) --no-run-if-empty -- \
    bullseye/*.bz2(N) -- \
    bunzip2 --force --verbose

rm -f -- {bullseye,bookworm,trixie}/*(NL0)
