#! /bin/zsh

setopt err_exit no_unset warn_create_global

autoload -U zargs

mkdir --parents bullseye bookworm trixie forky
mkdir --parents .etags logs/{bullseye,bookworm,trixie,forky}

BASE=https://deb.debian.org/

fetch() {
    local location=$1

    local url=$BASE$location
    local safename=${${url/#https:\/\/}//\//_}
    local suite=${${${(ps:/:)location}[3]}%-*}
    local filename=$suite/$safename
    local output=${filename/%.(bz2|xz)}
    local etagname=.etags/$safename
    local ref_time
    [[ -f $output ]] && ref_time=$output || ref_time="2004 Nov 13"

    () {
        echo "--- $url"
        curl --connect-timeout 5 --max-time 30 \
            --etag-compare $etagname \
            --etag-save $etagname \
            --time-cond $ref_time --output $filename $url
    } &> logs/$filename
}

locations=(
    debian/dists/bullseye/InRelease
    debian/dists/bullseye/contrib/binary-i386/Packages.xz
    debian/dists/bullseye/contrib/i18n/Translation-en.bz2
    debian/dists/bullseye/main/binary-i386/Packages.xz
    debian/dists/bullseye/main/i18n/Translation-en.bz2
    debian/dists/bullseye/non-free/binary-i386/Packages.xz
    debian/dists/bullseye/non-free/i18n/Translation-en.bz2
    debian/dists/bullseye-updates/InRelease
    debian/dists/bullseye-updates/contrib/binary-i386/Packages.xz
    debian/dists/bullseye-updates/contrib/i18n/Translation-en.bz2
    debian/dists/bullseye-updates/main/binary-i386/Packages.xz
    debian/dists/bullseye-updates/main/i18n/Translation-en.bz2
    debian/dists/bullseye-updates/non-free/binary-i386/Packages.xz
    debian/dists/bullseye-updates/non-free/i18n/Translation-en.bz2
    debian-security/dists/bullseye-security/InRelease
    debian-security/dists/bullseye-security/contrib/binary-i386/Packages.xz
    debian-security/dists/bullseye-security/contrib/i18n/Translation-en.xz
    debian-security/dists/bullseye-security/main/binary-i386/Packages.xz
    debian-security/dists/bullseye-security/main/i18n/Translation-en.xz
    debian-security/dists/bullseye-security/non-free/binary-i386/Packages.xz
    debian-security/dists/bullseye-security/non-free/i18n/Translation-en.xz

    debian/dists/bookworm/InRelease
    debian/dists/bookworm/contrib/binary-amd64/Packages.xz
    debian/dists/bookworm/contrib/i18n/Translation-en.xz
    debian/dists/bookworm/main/binary-amd64/Packages.xz
    debian/dists/bookworm/main/i18n/Translation-en.xz
    debian/dists/bookworm/non-free/binary-amd64/Packages.xz
    debian/dists/bookworm/non-free/i18n/Translation-en.xz
    debian/dists/bookworm/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/bookworm/non-free-firmware/i18n/Translation-en.xz
    debian/dists/bookworm-updates/InRelease
    debian/dists/bookworm-updates/contrib/binary-amd64/Packages.xz
    debian/dists/bookworm-updates/contrib/i18n/Translation-en.xz
    debian/dists/bookworm-updates/main/binary-amd64/Packages.xz
    debian/dists/bookworm-updates/main/i18n/Translation-en.xz
    debian/dists/bookworm-updates/non-free/binary-amd64/Packages.xz
    debian/dists/bookworm-updates/non-free/i18n/Translation-en.xz
    debian/dists/bookworm-updates/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/bookworm-updates/non-free-firmware/i18n/Translation-en.xz
    debian-security/dists/bookworm-security/InRelease
    debian-security/dists/bookworm-security/contrib/binary-amd64/Packages.xz
    debian-security/dists/bookworm-security/contrib/i18n/Translation-en.xz
    debian-security/dists/bookworm-security/main/binary-amd64/Packages.xz
    debian-security/dists/bookworm-security/main/i18n/Translation-en.xz
    debian-security/dists/bookworm-security/non-free/binary-amd64/Packages.xz
    debian-security/dists/bookworm-security/non-free/i18n/Translation-en.xz
    debian-security/dists/bookworm-security/non-free-firmware/binary-amd64/Packages.xz
    debian-security/dists/bookworm-security/non-free-firmware/i18n/Translation-en.xz

    debian/dists/trixie/InRelease
    debian/dists/trixie/contrib/binary-amd64/Packages.xz
    debian/dists/trixie/contrib/i18n/Translation-en.xz
    debian/dists/trixie/main/binary-amd64/Packages.xz
    debian/dists/trixie/main/i18n/Translation-en.xz
    debian/dists/trixie/non-free/binary-amd64/Packages.xz
    debian/dists/trixie/non-free/i18n/Translation-en.xz
    debian/dists/trixie/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/trixie/non-free-firmware/i18n/Translation-en.xz
    debian/dists/trixie-updates/InRelease
    debian/dists/trixie-updates/contrib/binary-amd64/Packages.xz
    debian/dists/trixie-updates/contrib/i18n/Translation-en.xz
    debian/dists/trixie-updates/main/binary-amd64/Packages.xz
    debian/dists/trixie-updates/main/i18n/Translation-en.xz
    debian/dists/trixie-updates/non-free/binary-amd64/Packages.xz
    debian/dists/trixie-updates/non-free/i18n/Translation-en.xz
    debian/dists/trixie-updates/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/trixie-updates/non-free-firmware/i18n/Translation-en.xz
    debian-security/dists/trixie-security/InRelease
    debian-security/dists/trixie-security/contrib/binary-amd64/Packages.xz
    debian-security/dists/trixie-security/contrib/i18n/Translation-en.xz
    debian-security/dists/trixie-security/main/binary-amd64/Packages.xz
    debian-security/dists/trixie-security/main/i18n/Translation-en.xz
    debian-security/dists/trixie-security/non-free/binary-amd64/Packages.xz
    debian-security/dists/trixie-security/non-free/i18n/Translation-en.xz
    debian-security/dists/trixie-security/non-free-firmware/binary-amd64/Packages.xz
    debian-security/dists/trixie-security/non-free-firmware/i18n/Translation-en.xz

    debian/dists/forky/InRelease
    debian/dists/forky/contrib/binary-amd64/Packages.xz
    debian/dists/forky/contrib/i18n/Translation-en.xz
    debian/dists/forky/main/binary-amd64/Packages.xz
    debian/dists/forky/main/i18n/Translation-en.xz
    debian/dists/forky/non-free/binary-amd64/Packages.xz
    debian/dists/forky/non-free/i18n/Translation-en.xz
    debian/dists/forky/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/forky/non-free-firmware/i18n/Translation-en.xz
    debian/dists/forky-updates/InRelease
    debian/dists/forky-updates/contrib/binary-amd64/Packages.xz
    debian/dists/forky-updates/contrib/i18n/Translation-en.xz
    debian/dists/forky-updates/main/binary-amd64/Packages.xz
    debian/dists/forky-updates/main/i18n/Translation-en.xz
    debian/dists/forky-updates/non-free/binary-amd64/Packages.xz
    debian/dists/forky-updates/non-free/i18n/Translation-en.xz
    debian/dists/forky-updates/non-free-firmware/binary-amd64/Packages.xz
    debian/dists/forky-updates/non-free-firmware/i18n/Translation-en.xz
    debian-security/dists/forky-security/InRelease
    debian-security/dists/forky-security/contrib/binary-amd64/Packages.xz
    debian-security/dists/forky-security/contrib/i18n/Translation-en.xz
    debian-security/dists/forky-security/main/binary-amd64/Packages.xz
    debian-security/dists/forky-security/main/i18n/Translation-en.xz
    debian-security/dists/forky-security/non-free/binary-amd64/Packages.xz
    debian-security/dists/forky-security/non-free/i18n/Translation-en.xz
    debian-security/dists/forky-security/non-free-firmware/binary-amd64/Packages.xz
    debian-security/dists/forky-security/non-free-firmware/i18n/Translation-en.xz
)
zargs --verbose --max-args 1 --max-procs $(nproc) -- $locations -- fetch

zargs --max-args 3 --max-procs $(nproc) --no-run-if-empty -- \
    {bullseye,bookworm,trixie,forky}/*.xz(N) -- \
    unxz --force --verbose
zargs --max-args 3 --max-procs $(nproc) --no-run-if-empty -- \
    bullseye/*.bz2(N) -- \
    bunzip2 --force --verbose

rm -f -- {bullseye,bookworm,trixie,forky}/*(NL0)

more logs/*/* | cat
