name: Scrape Debian package list data

on:
  push:
    paths:
      - ".github/workflows/scrape_data.yml"
      - "fetch_apt_lists"
  workflow_dispatch:
  schedule:
    - cron: "11 19 * * *"

permissions:
  contents: read

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache ETag data for fetcher
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/scrape_data.yml', 'fetch_apt_lists') }}
          path: .etags/

      - name: Install utilities
        run: |-
          sudo eatmydata apt-get -qq install --no-install-recommends zsh

      - name: Fetch package list data
        id: fetch_data
        run: |-
          echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
          ./fetch_apt_lists
          echo "end_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Commit, if changed
        id: commit
        env:
          FETCH_END_TIME: ${{ steps.fetch_data.outputs.end_time }}
          FETCH_START_TIME: ${{ steps.fetch_data.outputs.start_time }}
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all bookworm/ bullseye/ trixie/ forky/
          if ! git diff --staged --quiet; then
            modified_count=$(git status --porcelain bookworm/ bullseye/ trixie/ forky/ |
              grep -c '\.pkgs$' || :)
            runtime=$(( FETCH_END_TIME - FETCH_START_TIME ))
            git commit \
              -m "Update package lists ($(date -u +%FT%H:%M))" \
              --trailer "X-modified-lists: $modified_count" \
              --trailer "X-runtime: ${runtime}s"
            echo changed=true >> $GITHUB_OUTPUT
          fi

      - name: Push on main
        if: github.ref_name == 'main' && steps.commit.outputs.changed == 'true'
        env:
          GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |-
          git push https://x-access-token:$GH_PUSH_TOKEN@github.com/${{ github.repository }}

      - name: Upload logs on failure
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: logs
          path: logs/
          if-no-files-found: ignore
